---
# Configure DNS and DHCP services

- name: Configure DNS forwarding
  include_tasks: dns.yml

- name: Configure DHCP servers
  include_tasks: dhcp.yml

- name: Save services configuration
  vyos.vyos.vyos_config:
    save: true
